/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DayDayNumberRouteImport } from './routes/day/$dayNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayNumberRoute = DayDayNumberRouteImport.update({
  id: '/day/$dayNumber',
  path: '/day/$dayNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day/$dayNumber': typeof DayDayNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day/$dayNumber': typeof DayDayNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/day/$dayNumber': typeof DayDayNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day/$dayNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/day/$dayNumber'
  id: '__root__' | '/' | '/day/$dayNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DayDayNumberRoute: typeof DayDayNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$dayNumber': {
      id: '/day/$dayNumber'
      path: '/day/$dayNumber'
      fullPath: '/day/$dayNumber'
      preLoaderRoute: typeof DayDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DayDayNumberRoute: DayDayNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()



